# Generated by Django 4.1 on 2023-12-07 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.TextField(unique=True)),
                ('voters', models.ManyToManyField(related_name='voted_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
